/**
 * Remembers a referral code from the landing URL until the person signs up.
 *
 * `?ref=CODE` used to be generated by the invite button and read by nothing at
 * all, so every invite ever shared was decorative. The gap between clicking an
 * invite and finishing signup can be days and several page loads, so the code
 * is kept in localStorage rather than in the URL or in memory.
 */

const KEY = "gd-referral-code";
const STAMP = "gd-referral-seen-at";
const MAX_AGE_DAYS = 30;

/** Call on any page load — picks up ?ref= and cleans it out of the URL. */
export function captureReferralFromUrl() {
  if (typeof window === "undefined") return;
  try {
    const url = new URL(window.location.href);
    const code = (url.searchParams.get("ref") || "").trim().toUpperCase();
    if (!code) return;

    // Don't let a later click overwrite a code that's already waiting —
    // first invite wins, which is the fairer reading of "who referred them".
    if (!localStorage.getItem(KEY)) {
      localStorage.setItem(KEY, code);
      localStorage.setItem(STAMP, String(Date.now()));
    }

    // A referral code sitting in the address bar gets copied and shared by
    // accident, which attributes strangers to whoever first pasted the link.
    url.searchParams.delete("ref");
    window.history.replaceState({}, "", url.pathname + (url.searchParams.toString() ? `?${url.searchParams}` : "") + url.hash);
  } catch {
    /* private mode, or a URL we can't parse — nothing worth breaking over */
  }
}

export function pendingReferralCode(): string | null {
  if (typeof window === "undefined") return null;
  try {
    const code = localStorage.getItem(KEY);
    if (!code) return null;
    const seen = Number(localStorage.getItem(STAMP) ?? 0);
    if (seen && Date.now() - seen > MAX_AGE_DAYS * 86400000) {
      clearReferralCode();
      return null;
    }
    return code;
  } catch {
    return null;
  }
}

export function clearReferralCode() {
  try {
    localStorage.removeItem(KEY);
    localStorage.removeItem(STAMP);
  } catch {
    /* ignore */
  }
}

/**
 * Hands the stored code to the server once someone is signed in.
 * Safe to call on every load — the server no-ops if they already have one.
 */
export async function claimPendingReferral(): Promise<void> {
  const code = pendingReferralCode();
  if (!code) return;
  try {
    const fd = new FormData();
    fd.append("code", code);
    const res = await fetch("/api/referral", { method: "POST", body: fd });
    const r = await res.json().catch(() => ({}));
    // Clear on anything final. Only a transient failure is worth retrying,
    // and "not_signed_in" is transient by definition.
    if (r?.ok || (r?.reason && r.reason !== "not_signed_in")) clearReferralCode();
  } catch {
    /* offline — try again next load */
  }
}
