// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/setup-profile": {
    params: {};
  };
  "/gigs/:id": {
    params: {
      "id": string;
    };
  };
  "/worker/home": {
    params: {};
  };
  "/worker/dashboard": {
    params: {};
  };
  "/worker/earnings": {
    params: {};
  };
  "/worker/profile": {
    params: {};
  };
  "/organizer/home": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/setup-profile" | "/gigs/:id" | "/worker/home" | "/worker/dashboard" | "/worker/earnings" | "/worker/profile" | "/organizer/home" | "/sitemap.xml" | "/robots.txt";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/setup-profile.tsx": {
    id: "routes/setup-profile";
    page: "/setup-profile";
  };
  "routes/gigs.$id.tsx": {
    id: "routes/gigs.$id";
    page: "/gigs/:id";
  };
  "routes/public-layout.tsx": {
    id: "routes/public-layout";
    page: "/worker/home";
  };
  "routes/worker.home.tsx": {
    id: "routes/worker.home";
    page: "/worker/home";
  };
  "routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/worker/dashboard" | "/worker/earnings" | "/worker/profile" | "/organizer/home";
  };
  "routes/worker.dashboard.tsx": {
    id: "routes/worker.dashboard";
    page: "/worker/dashboard";
  };
  "routes/worker.earnings.tsx": {
    id: "routes/worker.earnings";
    page: "/worker/earnings";
  };
  "routes/worker.profile.tsx": {
    id: "routes/worker.profile";
    page: "/worker/profile";
  };
  "routes/organizer.home.tsx": {
    id: "routes/organizer.home";
    page: "/organizer/home";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/robots[.]txt.tsx": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/setup-profile": typeof import("./app/routes/setup-profile.tsx");
  "routes/gigs.$id": typeof import("./app/routes/gigs.$id.tsx");
  "routes/public-layout": typeof import("./app/routes/public-layout.tsx");
  "routes/worker.home": typeof import("./app/routes/worker.home.tsx");
  "routes/app-layout": typeof import("./app/routes/app-layout.tsx");
  "routes/worker.dashboard": typeof import("./app/routes/worker.dashboard.tsx");
  "routes/worker.earnings": typeof import("./app/routes/worker.earnings.tsx");
  "routes/worker.profile": typeof import("./app/routes/worker.profile.tsx");
  "routes/organizer.home": typeof import("./app/routes/organizer.home.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/robots[.]txt": typeof import("./app/routes/robots[.]txt.tsx");
};