// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/auth/reset": {
    params: {};
  };
  "/setup-profile": {
    params: {};
  };
  "/organizer/preview": {
    params: {};
  };
  "/gigs/:id": {
    params: {
      "id": string;
    };
  };
  "/hirer/:id": {
    params: {
      "id": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/api/apply": {
    params: {};
  };
  "/api/cancel": {
    params: {};
  };
  "/api/mark-attendance": {
    params: {};
  };
  "/api/pay": {
    params: {};
  };
  "/api/announce": {
    params: {};
  };
  "/api/qa": {
    params: {};
  };
  "/api/apply-internship": {
    params: {};
  };
  "/api/internship-applicants": {
    params: {};
  };
  "/api/export-applicants": {
    params: {};
  };
  "/api/bank": {
    params: {};
  };
  "/api/withdraw": {
    params: {};
  };
  "/api/cron/reminders": {
    params: {};
  };
  "/worker/home": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/worker/dashboard": {
    params: {};
  };
  "/worker/earnings": {
    params: {};
  };
  "/worker/profile": {
    params: {};
  };
  "/organizer/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/callback" | "/auth/reset" | "/setup-profile" | "/organizer/preview" | "/gigs/:id" | "/hirer/:id" | "/admin" | "/api/apply" | "/api/cancel" | "/api/mark-attendance" | "/api/pay" | "/api/announce" | "/api/qa" | "/api/apply-internship" | "/api/internship-applicants" | "/api/export-applicants" | "/api/bank" | "/api/withdraw" | "/api/cron/reminders" | "/worker/home" | "/about" | "/worker/dashboard" | "/worker/earnings" | "/worker/profile" | "/organizer/home";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/auth.reset.tsx": {
    id: "routes/auth.reset";
    page: "/auth/reset";
  };
  "routes/setup-profile.tsx": {
    id: "routes/setup-profile";
    page: "/setup-profile";
  };
  "routes/organizer.preview.tsx": {
    id: "routes/organizer.preview";
    page: "/organizer/preview";
  };
  "routes/gigs.$id.tsx": {
    id: "routes/gigs.$id";
    page: "/gigs/:id";
  };
  "routes/hirer.$id.tsx": {
    id: "routes/hirer.$id";
    page: "/hirer/:id";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/api.apply.ts": {
    id: "routes/api.apply";
    page: "/api/apply";
  };
  "routes/api.cancel.ts": {
    id: "routes/api.cancel";
    page: "/api/cancel";
  };
  "routes/api.mark-attendance.ts": {
    id: "routes/api.mark-attendance";
    page: "/api/mark-attendance";
  };
  "routes/api.pay.ts": {
    id: "routes/api.pay";
    page: "/api/pay";
  };
  "routes/api.announce.ts": {
    id: "routes/api.announce";
    page: "/api/announce";
  };
  "routes/api.qa.ts": {
    id: "routes/api.qa";
    page: "/api/qa";
  };
  "routes/api.apply-internship.ts": {
    id: "routes/api.apply-internship";
    page: "/api/apply-internship";
  };
  "routes/api.internship-applicants.ts": {
    id: "routes/api.internship-applicants";
    page: "/api/internship-applicants";
  };
  "routes/api.export-applicants.ts": {
    id: "routes/api.export-applicants";
    page: "/api/export-applicants";
  };
  "routes/api.bank.ts": {
    id: "routes/api.bank";
    page: "/api/bank";
  };
  "routes/api.withdraw.ts": {
    id: "routes/api.withdraw";
    page: "/api/withdraw";
  };
  "routes/api.cron.reminders.ts": {
    id: "routes/api.cron.reminders";
    page: "/api/cron/reminders";
  };
  "routes/public-layout.tsx": {
    id: "routes/public-layout";
    page: "/worker/home" | "/about";
  };
  "routes/worker.home.tsx": {
    id: "routes/worker.home";
    page: "/worker/home";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/worker/dashboard" | "/worker/earnings" | "/worker/profile" | "/organizer/home";
  };
  "routes/worker.dashboard.tsx": {
    id: "routes/worker.dashboard";
    page: "/worker/dashboard";
  };
  "routes/worker.earnings.tsx": {
    id: "routes/worker.earnings";
    page: "/worker/earnings";
  };
  "routes/worker.profile.tsx": {
    id: "routes/worker.profile";
    page: "/worker/profile";
  };
  "routes/organizer.home.tsx": {
    id: "routes/organizer.home";
    page: "/organizer/home";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/auth.reset": typeof import("./app/routes/auth.reset.tsx");
  "routes/setup-profile": typeof import("./app/routes/setup-profile.tsx");
  "routes/organizer.preview": typeof import("./app/routes/organizer.preview.tsx");
  "routes/gigs.$id": typeof import("./app/routes/gigs.$id.tsx");
  "routes/hirer.$id": typeof import("./app/routes/hirer.$id.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/api.apply": typeof import("./app/routes/api.apply.ts");
  "routes/api.cancel": typeof import("./app/routes/api.cancel.ts");
  "routes/api.mark-attendance": typeof import("./app/routes/api.mark-attendance.ts");
  "routes/api.pay": typeof import("./app/routes/api.pay.ts");
  "routes/api.announce": typeof import("./app/routes/api.announce.ts");
  "routes/api.qa": typeof import("./app/routes/api.qa.ts");
  "routes/api.apply-internship": typeof import("./app/routes/api.apply-internship.ts");
  "routes/api.internship-applicants": typeof import("./app/routes/api.internship-applicants.ts");
  "routes/api.export-applicants": typeof import("./app/routes/api.export-applicants.ts");
  "routes/api.bank": typeof import("./app/routes/api.bank.ts");
  "routes/api.withdraw": typeof import("./app/routes/api.withdraw.ts");
  "routes/api.cron.reminders": typeof import("./app/routes/api.cron.reminders.ts");
  "routes/public-layout": typeof import("./app/routes/public-layout.tsx");
  "routes/worker.home": typeof import("./app/routes/worker.home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/app-layout": typeof import("./app/routes/app-layout.tsx");
  "routes/worker.dashboard": typeof import("./app/routes/worker.dashboard.tsx");
  "routes/worker.earnings": typeof import("./app/routes/worker.earnings.tsx");
  "routes/worker.profile": typeof import("./app/routes/worker.profile.tsx");
  "routes/organizer.home": typeof import("./app/routes/organizer.home.tsx");
};